spring:
  application:
    name: gateway


server:
  port: 5000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost



logging:
  level:
    root: debug
