spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://CORE
          predicates:
            - Path=/user/**


server:
  port: 5000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost



logging:
  level:
    root: debug
