spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://CORE
          predicates:
            - Path=/**
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Content-Length, TOKEN, Authorization"
            allowCredentials: true
            maxAge: 3600

server:
  port: 5000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: gateway
    prefer-ip-address: true

logging:
  level:
    root: info
    reactor:
      netty: info
    org.springframework.cloud.gateway: trace

