spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://CORE
          predicates:
            - Path=/user/**
        - id: data
          uri: lb://DATA
          predicates:
            - Path=/data/**
        - id: scraper
          uri: lb://SCRAPER
          predicates:
            - Path=/scraper/**


server:
  port: 5000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server



logging:
  level:
    root: info
