spring:
  application:
    name: CORE
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: core
    prefer-ip-address: true
#    non-secure-port-enabled: true
#    secure-port-enabled: true
#    non-secure-port: 80
#    secure-port: 443


jwt:
  secret: iPVPTqbBv3EBcrKkPj9eNwDPSfVkYaDC9C2j6VxiPMxtxwC6GneLeqb6JJu2EyXEicWTjQzyWjbfKFy9jmT9NgMnMM7vC7ck

logging:
  level:
    root: info
