spring:
  application:
    name: core
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


jwt:
  secret: iPVPTqbBv3EBcrKkPj9eNwDPSfVkYaDC9C2j6VxiPMxtxwC6GneLeqb6JJu2EyXEicWTjQzyWjbfKFy9jmT9NgMnMM7vC7ck

logging:
  level:
    root: debug
