name: Deploy GCVM

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch name'
        default: 'main'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
    - run: echo "JDK 21 installed successfully!"

    # run clean package w/ multi-threading
    - run: mvn clean package -T 16

    # echo names of jars in target
    - run: |
        echo ./core/target/*.jar
        echo ./data/target/*.jar
        echo ./eureka-server/target/*.jar
        echo ./gateway/target/*.jar

    - name: Open SFTP Connection to VM
      uses: SamKirkland/FTP-Deploy-Action@v2.0.0  
      env: 
        FTP_SERVER: ${{secrets.VM_IP}}
        FTP_PASSWORD: ${{secrets.VM_SSH_KEY}}
        FTP_USERNAME: 'gogoasa'
        LOCAL_DIR: './core/target/maven-archiver/'
        METHOD: sftp
      
  
        
      # run: |
      #   echo $SSH_PRIVATE_KEY >> ssh_key && chmod 600 ssh_key
      #   sftp -v -o StrictHostKeyChecking=no -i ssh_key gogoasa@34.118.5.70
      #   put ./core/target/*.jar
      #   put ./data/target/*.jar
      #   put ./eureka-server/target/*.jar
      #   put ./gateway/target/*.jar


    
    
    
    
