name: Deploy Microservices to GCVM

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch name'
        default: 'main'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Services
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.name }}

    - name: Install JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -T 16
      
    - name: Move JARs to root
      run: |
        mv ./core/target/*.jar ./
        mv ./data/target/*.jar ./
        mv ./eureka-server/target/*.jar ./
        mv ./gateway/target/*.jar ./

    - name: Copy JARs to GCVM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: 'gogoasa'
        key: ${{ secrets.VM_SSH_KEY }}
        source: "./*.jar"
        target: "/home/gogoasa/webapp"
        port: 22
        overwrite: true

    - name: Restart GCVM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: 'gogoasa'
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo systemctl restart core.service
          sleep 10
          sudo systemctl restart data.service
          sleep 10
          sudo systemctl restart eureka-server.service
          sleep 10
          sudo systemctl restart gateway.service
    
