name: Deploy GCVM

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch name'
        default: 'main'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
    - run: echo "JDK 21 installed successfully!"

    # run clean package w/ multi-threading
    - run: mvn clean package -T 16

    # echo names of jars in target
    - run: |
        echo ./core/target/*.jar
        echo ./data/target/*.jar
        echo ./eureka-server/target/*.jar
        echo ./gateway/target/*.jar

    - name: Open SFTP Connection to VM
      env: 
        VM_IP: ${{secrets.VM_IP}}
        SSH_PRIVATE_KEY: ${{secrets.VM_SSH_KEY}}
      run: |
        echo $SSH_PRIVATE_KEY >> ssh_key && chmod +x ssh_key
        sftp -v -i ssh_key gogoasa@34.118.59.212
        put ./core/target/*.jar
        put ./data/target/*.jar
        put ./eureka-server/target/*.jar
        put ./gateway/target/*.jar


    
    
    
    
